[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "CHROMA_HOST,CHROMA_PORT,NEXT_PUBLIC_API_URL,NEXT_PUBLIC_API_ENDPOINT,DATABASE_URL,SECRET_KEY"
  DATABASE_URL = "${env.DATABASE_URL}"
  SECRET_KEY = "${env.SECRET_KEY}"
  OLLAMA_BASE_URL = "${env.OLLAMA_BASE_URL}"
  OLLAMA_DEFAULT_MODEL = "${env.OLLAMA_DEFAULT_MODEL}"
  OLLAMA_EMBED_MODEL = "${env.OLLAMA_EMBED_MODEL}"
  NEXT_PUBLIC_API_ENDPOINT = "${env.NEXT_PUBLIC_API_ENDPOINT}"
  NEXT_PUBLIC_API_URL = "${env.NEXT_PUBLIC_API_URL}"
  CHROMA_HOST = "${env.CHROMA_HOST}"
  CHROMA_PORT = "${env.CHROMA_PORT}"

[[plugins]]
  package = "@netlify/plugin-nextjs"
