from sqlalchemy import Column, String, Boolean, DateTime, ForeignKey, Text, Integer, JSON
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import relationship
from app.core.database import Base
import uuid
from datetime import datetime, timezone

def utcnow():
    return datetime.now(timezone.utc)

class Automation(Base):
    """Stores pre-defined or AI-generated workflow blueprints."""
    __tablename__ = "automations"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), index=True)
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    dag_definition = Column(JSONB, nullable=False) # The Graph structure
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), default=utcnow)
    updated_at = Column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    
    executions = relationship("WorkflowHistory", back_populates="automation", cascade="all, delete-orphan")
    scheduled_tasks = relationship("ScheduledTask", back_populates="automation", cascade="all, delete-orphan")
    user = relationship("User", backref="user_automations")

class WorkflowHistory(Base):
    """Tracks the lifecycle of a specific workflow instance."""
    __tablename__ = "workflow_history"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    automation_id = Column(UUID(as_uuid=True), ForeignKey("automations.id", ondelete="CASCADE"))
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"))
    status = Column(String(50), default="pending", index=True) # pending, running, completed, failed
    input_payload = Column(JSONB, default=dict)
    output_result = Column(JSONB, default=dict)
    error_log = Column(Text, nullable=True)
    started_at = Column(DateTime(timezone=True), default=utcnow)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    
    automation = relationship("Automation", back_populates="executions")
    logs = relationship("AutomationLog", back_populates="history", cascade="all, delete-orphan")
    user = relationship("User", backref="user_workflow_histories")

class Reminder(Base):
    """Time-based alerts for users."""
    __tablename__ = "reminders"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), index=True)
    content = Column(Text, nullable=False)
    due_at = Column(DateTime(timezone=True), nullable=False, index=True)
    status = Column(String(50), default="active") # active, completed, snoozed, dismissed
    priority = Column(Integer, default=3)
    metadata_json = Column(JSONB, default=dict)
    created_at = Column(DateTime(timezone=True), default=utcnow)
    
    user = relationship("User", backref="user_reminders")

class EmailDraft(Base):
    """Pending communications generated by AI."""
    __tablename__ = "email_drafts"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), index=True)
    recipient = Column(String(255), nullable=False)
    subject = Column(String(255))
    body = Column(Text)
    status = Column(String(50), default="draft") # draft, sent, discarded
    context_source_id = Column(UUID(as_uuid=True), nullable=True)
    created_at = Column(DateTime(timezone=True), default=utcnow)
    updated_at = Column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)
    
    user = relationship("User", backref="user_email_drafts")

class AutomationLog(Base):
    """Granular tracking for every node in the Task DAG."""
    __tablename__ = "automation_logs"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    history_id = Column(UUID(as_uuid=True), ForeignKey("workflow_history.id", ondelete="CASCADE"), index=True)
    step_id = Column(String(100), nullable=False) # ID from the DAG
    agent_name = Column(String(100), nullable=False)
    status = Column(String(50))
    input_data = Column(JSONB)
    output_data = Column(JSONB)
    retry_count = Column(Integer, default=0)
    created_at = Column(DateTime(timezone=True), default=utcnow)
    
    history = relationship("WorkflowHistory", back_populates="logs")

class ScheduledTask(Base):
    """Event-driven triggers (Webhooks, Time-based, or AI-Conditioned)."""
    __tablename__ = "scheduled_tasks"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), index=True)
    automation_id = Column(UUID(as_uuid=True), ForeignKey("automations.id", ondelete="SET NULL"), nullable=True)
    trigger_type = Column(String(50), nullable=False) # cron, webhook, ai_event
    schedule_expression = Column(String(100)) # cron expression
    last_run_at = Column(DateTime(timezone=True))
    next_run_at = Column(DateTime(timezone=True), index=True)
    is_enabled = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), default=utcnow)
    
    automation = relationship("Automation", back_populates="scheduled_tasks")
    user = relationship("User", backref="user_scheduled_tasks")
