"""Add profile fields and workspaces

Revision ID: 993a08f35ce0
Revises: 9295f05ab2e7
Create Date: 2026-05-20 22:37:00.477654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '993a08f35ce0'
down_revision: Union[str, Sequence[str], None] = '9295f05ab2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.add_column('users', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('dob', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('role_title', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('social_profiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('hobbies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('public_profile_url', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_public_profile_url'), 'users', ['public_profile_url'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_public_profile_url'), table_name='users')
    op.drop_column('users', 'public_profile_url')
    op.drop_column('users', 'hobbies')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'social_profiles')
    op.drop_column('users', 'role_title')
    op.drop_column('users', 'company')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
